### ISSUE TITLE
tpm2: Sign with hash ticket

### ISSUE THREAD

**Issue by mdempsky** [google/go-tpm#101]
The TPM2_Sign command includes a validation hashcheck ticket parameter, but this isn't exposed via the tpm2.Sign function API. This is relevant to restricted keys (i.e., tpm2.FlagRestricted, which is included in tpm2.FlagSignerDefault), because they need to make sure the hashed data did not start with TPM_GENERATED_VALUE.

**Comment by salrashid123** [comment]
+1   
i ran into this as well. 

I needed the AK to `Sign` something and would need the ticket provided by `Hash` to do that

it looks like even `Hash` takes the first handle bytes alone prematurely:
  https://github.com/google/go-tpm/blob/master/tpm2/tpm2.go#L1385

when it should be able to get the full struct:
  https://github.com/tpm2-software/tpm2-tools/blob/master/lib/tpm2.c#L966

- with `tpm2_tools`:
```
tpm2_createek -c ek.ctx -G rsa -u ek.pub
tpm2_createak -C ek.ctx -c ak.ctx -n ak.name -u ak.pub


echo "meet me at.." > message.txt

tpm2_hash -C e -g sha256 -o hash.bin -t ticket.bin message.txt

w/o ticket
tpm2_sign -c ak.ctx -g sha256 -o sig.rssa message.txt
  ERROR: Eys_Sign(0x3E0) - tpm:parameter(3):invalid ticket
  ERROR: Unable to run tpm2_sign

w/ ticket

tpm2_sign -c ak.ctx -g sha256 -o sig.rssa -t ticket.bin message.txt

tpm2_verifysignature -c ak.ctx -g sha256 -s sig.rssa -m message.txt
```

```
TPMT_TK_HASHCHECK – This ticket is used to indicate that a digest of external data is safe to sign
using a restricted signing key. A restricted signing key may only sign a digest that was produced by the
TPM. If the digest was produced from externally provided data, there needs to be an indication that the
data did not start with the same first octets as are used for data that is generated within the TPM. This
prevents “forgeries” of attestation data. This ticket is used to provide the evidence that the data used in
the digest was checked by the TPM and is safe to sign. Assuming that the external data is "safe", this
type of ticket is produced by TPM2_Hash() or TPM2_SequenceComplete() and used by TPM2_Sign().
```

**Comment by twitchy-jsonp** [comment]
It should be straightforward to allow you to sign while providing a hash ticket, as ATM [tpm2.Sign](https://github.com/google/go-tpm/blob/9cc5bb2cf703e5ec3b7393ad8c99bceb8e01ad4e/tpm2/tpm2.go#L1431) just passes nothing for that parameter.

Would that change be enough, or would you also need changes to `tpm2.Hash` as well?

**Comment by salrashid123** [comment]
i think `tpm2.Hash` needs to return the rest of the part of data struct it gets from the tpm as the `ticket`
...that ticket needs to get stuffed into the `Sign()` function

take a look at the `tpm2_tools` command sequence:   `tpm2_hash` outputs a ticket which must be provided to `tpm2_sign`  (i.,e if you ask the ak to sign arbitrary stuff, its not going to do so unless it knows the tpm hashed it...and its not going to hash any arbitrary bit of data on behalf of an AK (i.,e magic number prefix)...thats my read atleast).

**Comment by chrisfenner** [comment]
I started PR #178, went to create the new issue and found it already existed. 😊

Rather than commit a breaking change to `tpm2.Hash` (to add a new return parameter for the ticket) as well as to `tpm2.Sign` (to accept a new validation parameter, again for the ticket), I added new overloads of these functions: HashVerified and SignVerifiedHash.

It should be noted (so I did, in the function documentation) that the maximum amount of data you can hash with the one-shot `TPM2_Hash` command is implementation-dependent, depending on `MAX_DIGEST_BUFFER` which is only guaranteed by the spec to be up to 1,024 bytes. Some TPMs may support larger buffers, leading to code which works on some TPMs (like the simulator) but not others (like a real discrete TPM with limited RAM). For more than 1024 bytes of data, the sequence commands should be used, but these aren't yet implemented by go-tpm.

I filed issue #179 to track possibly extending the API for this.
