### ISSUE TITLE
tpm2: CreateKey should not return a tpmutil.Handle

### ISSUE THREAD

**Issue by mdempsky** [google/go-tpm#102]
The TPM2_Create command does not return a handle, but tpm2.CreateKey tries to decode and return one anyway, resulting in a bogus tpmutil.Handle value.

Relatedly, the TPM2_CreateLoaded command doesn't seem available.

**Comment by twitchyliquid64** [comment]
A quick glance at the command spec shows Create does not return a handle, yet we parse it out all the same and it still [works](https://github.com/google/go-attestation/blob/ac781802186cc2cde321faa5d7fdd593bd42a172/attest/tpm_linux.go#L399) ... unclear what I am missing here.

Once we figure out what those 4 bytes are, maybe what we can do is add to the docstring to indicate the returned handle has no meaningful value (rather than breaking the API).

As for **TPM2_CreateLoaded**, this is not implemented (but looks pretty straightforward?)

**Comment by awly** [comment]
We can also break the API and bump the Go module version

**Comment by josephlr** [comment]
@awly I looked into this a little more and apparently this `uint32` parameter is a length. Specifically for TPM2_Create and TPM2_Import there's a length parameter at the beginning of of the output buffer.

I have no idea why, it's not in the spec.

@mdempsky I'd review a patch that adds TPM2_CreateLoaded (should be fairly straightforward).

**Comment by josephlr** [comment]
Ok so [tpm2-tss skips over a response params size field](https://github.com/tpm2-software/tpm2-tss/blob/b55b642fc48b5a5cdbbf21e46397e5c8c2ecafcb/src/tss2-sys/sysapi_util.c#L134) if the returned Tag is `TPM2_ST_SESSIONS`

We're not correctly doing that, instead some of our commands just always assume that it will be there, or assume that it will not be there. See [how we deal with `paramSize` in `decodeUnseal`](https://github.com/google/go-tpm/blob/30f8389f7afbbd553e969bf7c59c54e0a83a3373/tpm2/tpm2.go#L798-L806).

We need to adjust `tpm2.runCommand` or `tpmutil.RunCommand` to properly do this check, and then stop having each individual command look for a random uint32 that it ignores.

**Comment by josephlr** [comment]
So this is mentioned in [Part 3 of the Spec](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38-code.pdf) (sections 4.2.1 and 4.3)
