### ISSUE TITLE
tpmutil does not compile with GOARCH=arm64

### ISSUE THREAD

**Issue by rjoleary** [google/go-tpm#146]
The error is `undefined: syscall.SYS_POLL`.

arm64 does not have `syscall.SYS_POLL`. Instead, the `syscall.SYS_PPOLL` syscall should be used. The functionality of the ppoll syscall is a superset of the poll syscall, so this should be relatively straightforward to fix.

**Comment by russellcardullo** [comment]
Hi @josephlr, I also ran into this issue as well.  Any chance you'll be making a new tagged release that includes this and some of the other changes since the v0.2.0 tag?

**Comment by josephlr** [comment]
@russellcardullo we've made a few breaking changes since 0.2, so the next release will be 0.3. If we're doing a breaking change, then there are some other cleanups and usability improvements we'd want to look into.

However, if you don't want to wait, `go.mod` supports picking a specific git revision, see the docs on [Pseudo-versions](https://golang.org/cmd/go/#hdr-Pseudo_versions) and an [example from `go-tpm-tools`](https://github.com/google/go-tpm-tools/blob/11174a785d29a1defcd7593b8d086d73a94f2f41/go.mod#L7).

**Comment by russellcardullo** [comment]
Thanks @josephlr.
