### ISSUE TITLE
ReadPCRs returns a maximum of 8 results

### ISSUE THREAD

**Issue by iolivergithub** [google/go-tpm#202]
Here is the code snipped

```go
    resp,err := tpm2.ReadPCRs(rwc,tpm2.PCRSelection{ tpm2.AlgSHA256 , []int{10,11,12,13,14,15,16,17,18,19,20} })

        fmt.Println("Err is *",err,"*")
        fmt.Println("length  ",len(resp))
        fmt.Println("resp  ",resp)
```

The result is:

```bash
Err is * <nil> *
length   8
resp   map[10:[233 78 123 248 213 96 73 135 44 139 238 32 208 223 134 159 56 215 159 209 85 238 17 216 216 249 145 194 75 85 102 54] 11:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 12:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 13:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 14:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 15:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 16:[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 17:[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]]
```

Same result, ie maximum of 8 PCRs returned for any combination of PCRs and PCR bank.

**Comment by ElMostafaIdrassi** [comment]
From the [spec](https://trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-3-Commands-01.38.pdf), a `TPM2_PCR_Read` command only returns 1 single `TPML_DIGEST`. Knowing that a `TPML_DIGEST` can contain **at most 8 digests**, I think it is safe to say that the `TPM` can **at most** return **8 PCRs Digests** per `TPM2_PCR_Read` command.

https://github.com/google/go-tpm/blob/ac5b427c06a867a3f94077b406507ec93f1e04e1/tpm2/tpm2.go#L180-L191

As you can see, the current implementation only runs the command once and expects the `TPM` to return all the selected `PCRs`. This works fine when you select up to 8 `PCRs`, but will return only the first 8 `PCRs` digests if you select more, as explained above.

In order to fix this, a similar approach to what `tpm2-tools` does is needed, that is, in the first call, send the whole `TPML_PCR_SELECTION` with all the wanted `PCR` bits set. After getting and parsing the first response, null out the bits of the `PCRs` we just retrieved in the `TPML_PCR_SELECTION`, check that it is not all zeroed out, then call `TPM2_PCR_READ` once more on the new `TPML_PCR_SELECTION`, etc...

**Comment by twitchy-jsonp** [comment]
As @ElMostafaIdrassi explained, a single call to read PCRs can only read a few PCRs at a time. In go-attestation, we read all the PCRs using a loop, like this:

https://github.com/google/go-attestation/blob/2453c8f39a4ff46009f6a9db6fb7c6cca789d9a1/attest/tpm.go#L232
