### ISSUE TITLE
TPM2: Certify makes use of hardcoded signature scheme

### ISSUE THREAD

**Issue by ElMostafaIdrassi** [google/go-tpm#210]
Hello everyone,

The implementation of `Certify` does not give the caller the ability to set the signature scheme but instead, it calls `encodeCertify` which sets it to the hardcoded value `AlgRSASSA, AlgSHA256`.

This works if the signing key has a signature scheme set to exactly `AlgRSASSA, AlgSHA256`, but will fail if it is anything else (i.e. 
`AlgRSASSA, AlgSHA1`, `AlgECDSA, AlgSHA256`...)

Here is a quick test that showcases this failure (it's the same as `TestCertify`, I just changed `AlgSHA256` to `AlgSHA1`)

```
func TestCertifySHA1(t *testing.T) {
	rw := openTPM(t)
	defer rw.Close()

	params := Public{
		Type:       AlgRSA,
		NameAlg:    AlgSHA256,
		Attributes: FlagSignerDefault,
		RSAParameters: &RSAParams{
			Sign: &SigScheme{
				Alg:  AlgRSASSA,
				Hash: AlgSHA1,
			},
			KeyBits: 2048,
		},
	}
	signerHandle, signerPub, err := CreatePrimary(rw, HandleOwner, pcrSelection7, emptyPassword, defaultPassword, params)
	if err != nil {
		t.Fatalf("CreatePrimary(signer) failed: %s", err)
	}
	defer FlushContext(rw, signerHandle)

	subjectHandle, subjectPub, err := CreatePrimary(rw, HandlePlatform, pcrSelection7, emptyPassword, defaultPassword, params)
	if err != nil {
		t.Fatalf("CreatePrimary(subject) failed: %s", err)
	}
	defer FlushContext(rw, subjectHandle)

	attest, sig, err := Certify(rw, defaultPassword, defaultPassword, subjectHandle, signerHandle, nil)
	if err != nil {
		t.Errorf("Certify failed: %s", err)
		return
	}

	attestHash := sha256.Sum256(attest)
	if err := rsa.VerifyPKCS1v15(signerPub.(*rsa.PublicKey), crypto.SHA256, attestHash[:], sig); err != nil {
		t.Errorf("Signature verification failed: %v", err)
	}

	t.Run("DecodeAttestationData", func(t *testing.T) {
		ad, err := DecodeAttestationData(attest)
		if err != nil {
			t.Fatal("DecodeAttestationData:", err)
		}
		params := Public{
			Type:       AlgRSA,
			NameAlg:    AlgSHA256,
			Attributes: FlagSignerDefault,
			RSAParameters: &RSAParams{
				Sign: &SigScheme{
					Alg:  AlgRSASSA,
					Hash: AlgSHA1,
				},
				KeyBits: 2048,
				// Note: we don't include Exponent because CreatePrimary also
				// returns Public without it.
				ModulusRaw: subjectPub.(*rsa.PublicKey).N.Bytes(),
			},
		}
		matches, err := ad.AttestedCertifyInfo.Name.MatchesPublic(params)
		if err != nil {
			t.Fatalf("AttestedCertifyInfo.Name.MatchesPublic error: %v", err)
		}
		if !matches {
			t.Error("Name in AttestationData doesn't match Public structure of subject")
		}
	})
}
```

The test fails with the error `parameter 2, error code 0x12 : unsupported or incompatible scheme`

Can we modify `Certify` so that it takes the sigScheme as an argument and gives the caller the ability to set it accordingly rather than harcode it to `AlgRSASSA, AlgSHA256` in `encodeCertify` ? I know this would break the API, but I can't think of anything better. I tried setting the hash alg of the sig scheme to `AlgNull` in vain, I kept getting `parameter 2, error code 0x3 : hash algorithm not supported or not appropriate`.

Cheers,

**Comment by chrisfenner** [comment]
Options I see

1. Break the API for 100% callers and take the signing scheme in the new API. Since this function is 3 years old, this is likely to break a lot of people.
1. Add a new API `CertifyEx` which is Certify but accepts the scheme. Deprecate current `Certify`.
1. Break the API for 0% callers, and set the scheme to NULL ('use whatever scheme is on the key') unless the key has NULL as its scheme (in which case, set it to SSA/SHA256 like today). Transparently adds another ReadPublic call inline (ew)
1. Break the API for some smaller % of callers who call Certify on AKs that don't have signing schemes set, by unconditionally setting the scheme to NULL (so any caller using a key that doesn't have a scheme set, will fail)
   1. google/go-attestation [sets a scheme](https://github.com/google/go-attestation/blob/1045ef6327a28e3a9c7a5012fc2aea772c2f1216/attest/tpm.go#L48-L59) on its AK
   1. All the unit tests for google/go-tpm [set a scheme](https://github.com/google/go-tpm/blob/master/tpm2/test/tpm2_test.go) on the keys they use for Certify

I think (2) is the least headache but (4) can be good with good release notes.

**Comment by ElMostafaIdrassi** [comment]
@chrisfenner
Thank you for your reponse. Option 2 seems to be the best choice that breaks nothing. I am going to propose a PR for this if you don't mind.

However, although what you've stated in option 4 is correct and corresponds to what the documentation says, setting `scheme` to `tpmtSigScheme{AlgNull, AlgSHA256}` or to `tpmtSigScheme{AlgNull, AlgSHA1}` fails with the following error `handle 0, error code 0x15 : structure is the wrong size`. Any idea on why this is happening ?

**Comment by chrisfenner** [comment]
If you send the PR, I will take a look! I am a newer reviewer in this repo, so I may ask another owner for final approval and merge.

Option 4 is broken for go-tpm because `tpmtSigScheme` is not a perfect reflection of TPMT_SIG_SCHEME:
https://github.com/google/go-tpm/blob/240a3433a7a53049ab3386b7dace1e4d90dba2ce/tpm2/structures.go#L621-L624

![image](https://user-images.githubusercontent.com/61842497/90257596-3e9a0600-ddfc-11ea-8197-425f4cbc545d.png)

**Fast details:**
Almost all signature schemes except ECDAA and ALG_NULL take an additional hash algorithm parameter. To accommodate properly serializing either an ECDAA scheme or the NULL scheme, we will have to turn `tpmtSigScheme` into a smarter type with its own `Encode` and `Decode...` functions that understands that the serialization format depends on the overall scheme selector. (I don't think we need to add support for ECDAA at this point, so I propose leaving in the Hash field but not serializing it if Scheme is ALG_NULL)

**Boring details:**
TPMT_SIG_SCHEME is a `TPMT`, which means it contains a union and a tagged selector. In this case, the `scheme` field should select which type the `details` field conforms to. The latest spec has some (see [Part 2: Structures](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part2_Structures_pub.pdf), section 4.12) "Algorithm Macros" like `!ALG.ax` for explaining how a TPM algorithm xxx of type `a` (asymmetric) and `x` (signing) must have its own `TPMS_SCHEME_xxx`.

So we see that if we set `RSAPSS` as the scheme, then the `details` must be TPMS_SIG_SCHEME_RSAPSS. This scheme, like all RSA signature schemes, is an alias of `TPMS_SCHEME_HASH` generated by table 11.2.1.2. So RSASSA with SHA256 is 4 bytes long {0x00, 0x14, 0x00, 0x0b} for `TPM_ALG_RSASSA` followed by `TPM_ALG_SHA256`.

But, if we set `NULL` as the scheme instead, then `details` is null (empty) and therefore the full serialization of the null scheme is just 2 bytes long, {0x00, 0x10} for `TPM_ALG_NULL` with nothing after it.

**Comment by ElMostafaIdrassi** [comment]
Thanks for this great and very thorough explanation! Indeed, now I see how `tpmtSigScheme` should be changed to better reflect the official `TPMT_SIG_SCHEME`, even though it would mean quite a lot of work.

One last remark about the `Certify` function : I am a little bit confused about 2 of its arguments, that is `parentAuth` and `ownerAuth`. Shouldn't they be called `objectAuth` and `signerAuth` instead ? There is no mention of the parent / owner authentication in the doc, so I guess these were just typos.

**Comment by chrisfenner** [comment]
Of course, happy to help share info!

You're exactly right. Feel free to include a fix for these typos in your PR - this won't break builds but it will help document the actual current behavior of the function.
