### ISSUE TITLE
Add TPM2 unique field to Public type

### ISSUE THREAD

**Issue by dpsmith** [google/go-tpm#238]
The unique field in the Public template is used by TPM2_CreatePrimary in generating the Name and therefore indirectly incorporated into the RNG seed affecting the key generation. Without this, it is not possible to generate a unique primary, both in key and name, for any given algorithm. While the inSensitive->data is feed into RNG seed and thus affecting the key generation, it is not included in generating the name.

**Comment by chrisfenner** [comment]
Hi dpsmith@, because of your comment I learned something and wanted to add to this bug:

Section 28.2 Derivation Parameters in [Part 1](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf):

> Most KDFs require additional parameters in order to have different types of keys derived for different applications. The TPM allows two additional parameters (label and context) to be provided in TPM2_CreateLoaded(). These additional parameters can be provided in two ways: in the unique field of the inPublic value, or in the data field of the inSensitive parameter. If provided in the unique field, the corresponding value in the inSensitive.data field is ignored.

I did want to clarify that the true Name of the generated object will be based on the actual generated key's unique value (public key for RSA/ECC, obfuscation value for symmetric objects) in `unique`. Whether the key had label/context parameters mixed in from inSensitive.Data or inPublic.unique, the Name cannot be directly computed from the input template to CreatePrimary/Loaded.

https://github.com/google/go-tpm/blob/4347b8d6b884fa39ac65a6bac410ea1aa50e671c/tpm2/structures.go#L59

The `Public` struct currently combines parameters and unique into `RSAParameters`, `ECCParamters`) etc - if you drill into these, you should see that we have both the schemes/algorithm options as well as the "unique" public key etc in those structs. So, I think that if you set those in the `Public` passed into CreatePrimary, you should get what you want (the ability to customize deterministic key generation in the public template).

**Comment by dpsmith** [comment]
Thank you so much for the quick response!

For the {*}Parameters types, now I see what is being done here, thank you for pointing this out. A suggestion that I would have found helpful is if there was a comment that this is the packed unique field.

Apologies you are correct regarding what feeds into the generating of the actual Name versus the computed Name for RNG seeding. To help clarify why I am seeking to use unique over inSensitive is because of it's effects on attributes.

Section 27.3.3 Sensitive Values: data of [Part 1](https://trustedcomputinggroup.org/wp-content/uploads/TCG_TPM2_r1p59_Part1_Architecture_pub.pdf):

> This contains information that the caller wants to be incorporated in the sensitive part of the created object. This may be either a symmetric key or user data. If data is an Empty Buffer, then the sensitiveDataOrigin attribute of the template is required to be SET. If data is not empty, then sensitiveDataOrigin is required to be CLEAR.

For the new "[TPM 2.0 Keys for Device Identity and Attestation](https://trustedcomputinggroup.org/wp-content/uploads/TCG_IWG_DevID_v1r2_02dec2020.pdf)" specification, the solution I am working that is based on this specification and requires the ability to have multiple unique primaries. While the primaries themselves will not be the backing key for the AK/IDevID/LDevID, it is in the hierarchy that will be verified by the CA and will be expecting the SDO attribute to be set.

**Comment by chrisfenner** [comment]
I think a comment is needed, if we can't afford a refactor to separate `parameters` from `unique` (though I assume that such a refactor would be very disruptive to current callers of this code).

I think your solution should be enabled by e.g., directly setting `ModulusRaw` in the input template's `RSAParameters` field in the case of an RSA primary key - does that work?
https://github.com/google/go-tpm/blob/4347b8d6b884fa39ac65a6bac410ea1aa50e671c/tpm2/structures.go#L203

Thanks
Chris
